spi:
  clk_pin: ${pin_clk}
  mosi_pin: ${pin_mosi}
  miso_pin: ${pin_miso}

sx127x:
  dio0_pin: ${pin_dio0}
  cs_pin: ${pin_cs}
  rst_pin: ${pin_rst}
  pa_pin: BOOST
  pa_power: 8
  bandwidth: 125_0kHz
  crc_enable: true
  frequency: 433920000
  modulation: LORA
  rx_start: true
  sync_value: 0x12
  spreading_factor: 7
  coding_rate: CR_4_5
  preamble_size: 6

sensor:
  - platform: wifi_signal
    id: wifi_signal_db
    name: "WiFi Signal Strength"
    update_interval: 5s
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
      icon: mdi:ip
    ssid:
      name: SSID
      icon: mdi:wifi
    mac_address:
      name: MAC
      icon: mdi:ethernet
