substitutions:
  name: tank-factory
  ap_password: "12345678"

esphome:
  name: "${name}"
  friendly_name: "${name}"
  name_add_mac_suffix: True
  project:
    name: "walaworks.motorwala_tank"
    version: "1.0.0"

esp8266:
  board: esp01_1m

safe_mode:
  disabled: True

logger:

api:

ota:
  platform: esphome

dashboard_import:
  package_import_url: github://wala-works/motorwala/tank/factory.yaml@main
  import_full_config: false # or true
  refresh: 1h

wifi:
  ap:
    ssid: "${name} Hotspot"
    password: "${ap_password}"

captive_portal:

packages:
  common: !include common.yaml
